version: "3.8"

services:
  # Agent: runs on every GPU node, collects metrics and pushes to hub
  agent:
    image: cudascope/cudascope:latest
    command: ["--mode=agent", "--hub-url=http://hub:9090"]
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.gpu == true
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 128M
    networks:
      - cudascope

  # Hub: central server with UI and storage
  hub:
    image: cudascope/cudascope:latest
    command: ["--mode=hub"]
    ports:
      - "9090:9090"
    volumes:
      - cudascope-data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - CUDASCOPE_DATA_DIR=/data
    networks:
      - cudascope

volumes:
  cudascope-data:

networks:
  cudascope:
    driver: overlay
